# define environment
os: linux
dist: redhat

# define language
language: shell

# only build PRs against master branch or pushes to master branch
branches:
  only:
    - master

# export global variables into shell
env:
  global:
    # setting the version of terraform
    - tf_version=1.1.5

    # setting the terraform init cli options
    - tf_cli_options=" -input=false"

    # set terraform validation cli options
    - tf_validation_cli_options=""

    # set terraform paln cli options
    - tf_plan_cli_options=" -lock=false -input=false"

    # set terraform apply cli options
    - tf_apply_cli_options=" -auto-approve -input-false"

  jobs:
    include:
      - stage: terraform plan

        # terraform plan: as part of a pull request or kicked off by an api
        if: type IN (pull_request, api)

        install:
          # download and install terraform before each run
          - wget https://releases.hashicorp.com/terraform/"$tf_version"/
          terraform_"$tf_version"_linux_amd64.zip
          - unzip terraform_"$tf_version"_linux_amd64.zip
          - sudo mv terraform /usr/local/bin/
          - rm terraform_"$tf_version"_linux_amd64.zip

        script:
          # check if terraform fmt correct. If not, fail validation
          - echo "Validating Terraform fmt"
          - terraform fmt -recursive -check

          - echo "Pull request detected, creating change plan"

          # Terraform init, validate, then create change plan. If any fail, fail validation
          - terraform init $tf_init_cli_options
          - terraform validate $tf_validation_cli_options
          - terraform plan $tf_plan_cli_options

      - stage: terraform apply

        # terraform apply: only when pushing direct to master, or when pr merge into master
        if: type IN (push) and branch = master

        install:
          # download and install terraform before each run
          - wget https://releases.hashicorp.com/terraform/"$tf_version"/
          terraform_"$tf_version"_linux_amd64.zip
          - unzip terraform_"$tf_version"_linux_amd64.zip
          - sudo mv terraform /usr/local/bin/
          - rm terraform_"$tf_version"_linux_amd64.zip

        script:
          - echo "Merge detected, executing changes"

          # Terraform init and then apply changes to environment
        - terraform init $tf_init_cli_options
        - terraform apply $tf_apply_cli_options

